### ISSUE TITLE
[ToDo] Import Less functions as tree-shakeable exports

### ISSUE THREAD

**Issue by matthew-dean** [jesscss/jess#12]
### Description

Less contains a number of useful functions. They can be converted to ES modules and be a generic package for import.

### Requirements 

- [x] Create a `@jesscss/fns` package
- [ ] Copy in Less functions and re-factor into TS as individual files (one file per function).  (Note -- in some cases, some functions won't be useful to Jess and shouldn't be imported, such as functions that test if a node is of a certain Less type. Should we make a `@todo` of all functions?)
- The goal is to make these functions individually-importable / tree-shakeable!

### Use case

```less
// Verify Rollup / Webpack only tree-shake out used functions
@import { lighten } from '@jesscss/fns';

.box {
  color: lighten(#a1a1a1, 20%);
}
```
