### ISSUE TITLE
Issue parsing `*::before`

### ISSUE THREAD

**Issue by matthew-dean** [jesscss/jess#30]
**Describe the bug**
Issue in parsing the following:
```css
*, *::before, *::after {
  box-sizing: inherit;
}
```
Somehow this got missed in parsing tests. Looks like the issue is specifically with `*::before`, because `::before` seems to work.

**Jess version**
1.0.8-alpha.5
