### ISSUE TITLE
`var()` conversions from JS expressions not working yet with functions

### ISSUE THREAD

**Issue by matthew-dean** [jesscss/jess#32]
**Describe the bug**
Conversions from `$expr` to `var()` are not really working yet.

**Jess version**
1.0.8-alpha.6

**To Reproduce**
Set compiler mode to `dynamic` with this code:
```less
@import { contrast } from '@jesscss/fns';
@let color: #ff00ff;
.button {
  color: contrast($color);
}
```
`$color` will be converted to a `var()`, meaning it's not evaluate-able as a color, and therefore is not a valid argument for this JS function.

Need to do some more work / tests to convert JS expressions (as a last pass?) and functions to `var()`.
